Add contracts endpoint
safe-global/safe-decoder-service pull request #31
Opened 2024-12-17 18:20 UTC by moisses89

Close #12

2024-12-19 17:03 UTC, Uxio0 requested changes

2024-12-19 17:03 UTC, Uxio0 commented on app/datasources/db/models.py
> +    abi_hash: bytes | None = Field(nullable=False, index=True, unique=True)
If this is not `nullable`, how can it be `None`?

2024-12-19 17:03 UTC, Uxio0 commented on app/datasources/db/models.py
> +from app.datasources.db.utils import get_md5_abi_hash
Use relative import

2024-12-19 17:03 UTC, Uxio0 commented on app/datasources/db/models.py
> +    async def create(self, session):
Annotate types when possible

2024-12-19 17:03 UTC, Uxio0 commented on app/routers/about.py
> +from app.routers.models import About
Relative import

2024-12-19 17:03 UTC, Uxio0 commented on app/routers/contracts.py
> +    pagination_params: PaginationParams = Depends(),
```suggestion
    pagination_params: PaginationQueryParams = Depends(),
```

2024-12-19 17:03 UTC, Uxio0 commented on app/routers/contracts.py
> +    contracts_service = ContractService(request)
Passing the `request` to the service and instantiating one service for every client does not sound right to me

2024-12-19 17:03 UTC, Uxio0 commented on app/routers/models.py
> +    def convert_to_checksum_address(cls, address):
types

2024-12-19 17:03 UTC, Uxio0 commented on app/services/contract.py
> +from app.services.pagination import GenericPagination, PaginatedResponse
Relative imports

2024-12-20 09:51 UTC, moisses89 commented on app/datasources/db/models.py
> +    abi_hash: bytes | None = Field(nullable=False, index=True, unique=True)
It is the same as the primary key, setting `nullable=True` and `None` as secondary type let us to don´t pass abi_hash when you instantiate it. At this way we are able to do `Abi(abi_json=abi_json) `and calculate the `abi_hash` on create function.

2024-12-24 09:57 UTC, Uxio0 approved these changes

2024-12-26 10:22 UTC, merged